modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="tpsultimate"
version="1.0.0" 
displayName="Tps Ultimate"  
authors="Korrona"
description="A mod to display TPS information in Minecraft."  

[[dependencies.tpsultimate]]
modId="forge"
mandatory=true
versionRange="[36.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.tpsultimate]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
